Fix/get user real
craigostrin/fistbump pull request #35
Opened 2023-08-26 13:37 UTC by craigostrin

2023-08-28 07:17 UTC, bienmag commented on apps/client/app/employee/[id]/new-review/page.tsx
it's already in main

2023-08-28 07:18 UTC, bienmag requested changes

2023-08-28 07:18 UTC, bienmag commented on apps/client/app/employee/[id]/new-review/page.tsx
> +  const user = await getUser(userQuery, { id: params.id })
it's already in main

2023-08-28 10:39 UTC, bienmag commented
what should we do with this?

2023-08-29 09:40 UTC, craigostrin commented
outdated

2023-08-29 09:40 UTC, closed without merging