shadncn setup done
craigostrin/fistbump pull request #9
Opened 2023-08-21 15:46 UTC by hrvojevincek

2023-08-21 16:42 UTC, bienmag requested changes
![image](https://github.com/craigostrin/fistbump/assets/106547933/89365209-3d8e-4635-8194-68fb8dad1f03)

2023-08-21 16:44 UTC, bienmag commented
I'm trying to use the Button like this but it doesnt work for me 
 
![image](https://github.com/craigostrin/fistbump/assets/106547933/9c962af0-bd57-444a-8019-c9b946f82420)

2023-08-21 17:44 UTC, hrvojevincek commented
It is working now. please merge. spasiba

2023-08-22 07:17 UTC, bienmag approved these changes

2023-08-22 08:06 UTC, merged